ASSUME DS:DATA,CS:CODE
DATA SEGMENT
MSG DB 0AH,0DH,"ENTER FIRST NUMBER:$"
MSG1 DB 0AH,0DH,"ENTER SECOND NUMBER:$"
MSG2 DB 0AH,0DH,"THE SUM IS:$"
MSG3 DB 0AH,0DH,"THE DIFFERENCE IS:$"
DATA ENDS
CODE SEGMENT
START:
    MOV AX,DATA
    MOV DS,AX
    LEA DX,MSG
    MOV AH,09H
    INT 21h
    MOV AH,01H
    INT 21H
    MOV BH,AL
    MOV AH,01H
    INT 21H
    MOV BL,AL    
    LEA DX,MSG1
    MOV AH,09H
    INT 21h
    MOV AH,01H
    INT 21H
    MOV CH,AL
    MOV AH,01H
    INT 21H
    MOV CL,AL
    MOV AL,BL
    MOV AH,00H
    ADD AL,CL
    aaa
    ADD AX,3030H
    MOV BL,AL
    MOV AL,AH
    MOV AH,00H
    ADD AL,BH
    ADD AL,CH
    aaa
    ADD AX,3030H
    MOV BH,AL
    MOV CL,AH
    LEA DX,MSG2
    MOV AH,09H
    INT 21H
    MOV DL,CL
    MOV AH,02H
    INT 21H
    MOV DL,BH
    MOV AH,02H
    INT 21H
    MOV DL,BL
    MOV AH,02H
    INT 21H
    MOV AH,04CH
    INT 21H
CODE ENDS
END START  
    
    


