ASSUME DS:DATA,CS:CODE
DATA SEGMENT
MSG DB 0AH,0DH,"ENTER FIRST NUMBER:$"
MSG1 DB 0AH,0DH,"ENTER SECOND NUMBER:$"
MSG2 DB 0AH,0DH,"THE SUM IS:$"
DATA ENDS


CODE SEGMENT
START:
    MOV AX,DATA
    MOV DS,AX

   ;DISPLAY THE MESSAGE

    LEA DX,MSG
    MOV AH,09H
    INT 21h

   ;READ THE FIRST NUMBER

    MOV AH,01H
    INT 21H
    MOV BH,AL;STORE THE FIRST HIHER NIBBLE NUMBER IN BH

    MOV AH,01H
    INT 21H
    MOV BL,AL;STORE THE SECOND LOWER NIBBLE NUMBER IN BL

  ;DISPLAY THE MESSAGE

    LEA DX,MSG1
    MOV AH,09H
    INT 21h

   ;READ THE SECOND NUMBER

    MOV AH,01H
    INT 21H
    MOV CH,AL;STORE THE FIRST HIHER NUMBER IN CH
    MOV AH,01H
    INT 21H
    MOV CL,AL;STORE THE SECOND LOWER NUMBER IN CL

   ;ADD THE TWO NUMBERS
   ;ACTUALLY THE NUMBERS IN BX AND CX
    MOV AL,BL
    MOV AH,00H ;FOR CARRY
    sub AL,CL;ADD THE LOWER NIBBLE NUMBERS
    AAS
    ADD AX,3030H ;CONVERT THE ASCII CODE TO BINARY


    MOV BL,AL;STORE THE SUM IN BL

    MOV AL,AH;CARRY TO AL
    MOV AH,00H
    ADD AL,BH;ADD THE CARRY TO THE FIRST NUMBER
    sub AL,CH;ADD THE SECOND NUMBER
    AAS
    ADD AX,3030H


    MOV BH,AL;STORE THE SUM IN BH

    MOV CL,AH;CARRY TO CL

    ;DISPLAY THE MESSAGE
    LEA DX,MSG2
    MOV AH,09H
    INT 21H

    ;DISPLAY THE SUM
    MOV DL,CL
    MOV AH,02H
    INT 21H;DISPLAY THE CARRY

    MOV DL,BH
    MOV AH,02H
    INT 21H;DISPLAY THE FIRST NUMBER

    MOV DL,BL
    MOV AH,02H
    INT 21H;DISPLAY THE SECOND NUMBER

    MOV AH,04CH
    INT 21H;TERMINATE THE PROGRAM
CODE ENDS
END START